global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "wifi_sensor"
    static_configs:
      - targets: ["localhost:5000"]
    metrics_path: "/metrics"

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
